name: Push Dockerfile

on:
  workflow_dispatch:
    inputs:
        project:
            description: 'Project name to build and push Docker image'
            required: true
            default: 'clients/fractiunate-ssr'
            type: choice
            options:
            - 'clients/fractiunate-ssr'
            - 'server/node/node-dummy-server'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - id: replace-project
        name: Replace project name
        shell: bash
        run: echo "project=$(echo '${{ github.event.inputs.project }}' | sed 's/\//-/g')" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            docker.io/fractiunate/${{ steps.replace-project.outputs.project }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=sha
          labels: |
            org.opencontainers.image.authors=fractiunate
    
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ github.event.inputs.project }}
          push: true
          build-args: |
            NODE_ENV=production
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}